name: Docker Tools Deploy
on:
  release:
    types: [published]

jobs:
  build:
    name: Dockerize
    env:
      repo_name: komodohealth/nvs
      image_tag: rbac
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Get Latest Version Number
        run: |
          echo 'version<<EOF' >> $GITHUB_ENV
          curl -s https://api.github.com/repos/micurley/docker-tools/releases/latest | jq -r .tag_name >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "$version"
      - name: Login to DockerHub Registry
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build  Docker Image
        run: |
          echo "sha=$GITHUB_SHA" >> $GITHUB_ENV
          docker build . --file deploy/production/Dockerfile --tag ${{ env.repo_name }}:${{ env.image_tag }} --build-arg version
      - name: Push Updated Docker Image
        if: success()
        run: |
          docker tag ${{ env.repo_name }}:${{ env.image_tag }} ${{ env.repo_name }}:${{ env.image_tag }}_${{ env.version }}
          docker tag ${{ env.repo_name }}:${{ env.image_tag }} ${{ env.repo_name }}:${{ env.image_tag }}-$GITHUB_SHA
          docker push ${{ env.repo_name }}:${{ env.image_tag }}_${{ env.version }}
          docker push ${{ env.repo_name }}:${{ env.image_tag }}-${{ env.sha }}
